import type { Guardian, AcademicClass, StudentDetail } from '../types';

/**
 * Mock Guardians data for development
 */
export const mockGuardians: Guardian[] = [
  {
    id: 'g1',
    firstName: 'Ahmed',
    lastName: 'Rahman',
    relationship: 'Father',
    contactNumber: '+880171234567',
    email: 'ahmed.rahman@email.com',
    address: '123 Main Street, Dhaka',
    occupation: 'Engineer',
    nid: '1234567890123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'g2',
    firstName: 'Fatima',
    lastName: 'Khan',
    relationship: 'Mother',
    contactNumber: '+880181234567',
    email: 'fatima.khan@email.com',
    address: '456 Park Avenue, Chittagong',
    occupation: 'Teacher',
    nid: '2345678901234',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'g3',
    firstName: 'Mohammad',
    lastName: 'Ali',
    relationship: 'Father',
    contactNumber: '+880191234567',
    email: 'mohammad.ali@email.com',
    address: '789 Garden Road, Sylhet',
    occupation: 'Doctor',
    nid: '3456789012345',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'g4',
    firstName: 'Sarah',
    lastName: 'Ahmed',
    relationship: 'Mother',
    contactNumber: '+880161234567',
    email: 'sarah.ahmed@email.com',
    address: '321 Lake View, Rajshahi',
    occupation: 'Lawyer',
    nid: '4567890123456',
    createdAt: new Date().toISOString(),
  },
];

/**
 * Mock Academic Classes data for development
 */
export const mockAcademicClasses: AcademicClass[] = [
  {
    id: 'ac1',
    name: 'Class 9',
    section: 'A',
    academicYear: '2024',
    description: 'Science Section',
    capacity: 40,
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ac2',
    name: 'Class 9',
    section: 'B',
    academicYear: '2024',
    description: 'Commerce Section',
    capacity: 35,
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ac3',
    name: 'Class 10',
    section: 'A',
    academicYear: '2024',
    description: 'Science Section',
    capacity: 38,
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ac4',
    name: 'Class 10',
    section: 'B',
    academicYear: '2024',
    description: 'Arts Section',
    capacity: 32,
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
];

/**
 * Mock Students data for development
 */
export const mockStudents: StudentDetail[] = [
  {
    id: 's1',
    firstName: 'Rashid',
    lastName: 'Hassan',
    registrationNumber: 'REG2024001',
    dateOfBirth: '2008-05-15T00:00:00Z',
    gender: 'Male',
    bloodGroup: 'A+',
    contactNumber: '+880171111111',
    email: 'rashid.hassan@student.edu',
    address: 'House 12, Road 5, Dhanmondi, Dhaka',
    emergencyContact: '+880171234567',
    medicalConditions: 'None',
    guardianId: 'g1',
    academicClassId: 'ac1',
    roomId: '1',
    bedId: '2',
    guardian: mockGuardians[0],
    academicClass: mockAcademicClasses[0],
    room: {
      id: '1',
      roomNumber: '101',
      floor: '1st Floor',
      building: 'Main Building',
    },
    bed: {
      id: '2',
      bedNumber: '101-B',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 's2',
    firstName: 'Amina',
    lastName: 'Begum',
    registrationNumber: 'REG2024002',
    dateOfBirth: '2008-08-22T00:00:00Z',
    gender: 'Female',
    bloodGroup: 'B+',
    contactNumber: '+880181111111',
    email: 'amina.begum@student.edu',
    address: 'Flat 3B, Green Tower, Chittagong',
    emergencyContact: '+880181234567',
    medicalConditions: 'Asthma',
    guardianId: 'g2',
    academicClassId: 'ac1',
    guardian: mockGuardians[1],
    academicClass: mockAcademicClasses[0],
    createdAt: new Date().toISOString(),
  },
  {
    id: 's3',
    firstName: 'Karim',
    lastName: 'Uddin',
    registrationNumber: 'REG2024003',
    dateOfBirth: '2007-12-10T00:00:00Z',
    gender: 'Male',
    bloodGroup: 'O+',
    contactNumber: '+880191111111',
    email: 'karim.uddin@student.edu',
    address: 'Village: Goalpar, Sylhet',
    emergencyContact: '+880191234567',
    guardianId: 'g3',
    academicClassId: 'ac3',
    guardian: mockGuardians[2],
    academicClass: mockAcademicClasses[2],
    createdAt: new Date().toISOString(),
  },
  {
    id: 's4',
    firstName: 'Nadia',
    lastName: 'Islam',
    registrationNumber: 'REG2024004',
    dateOfBirth: '2008-03-18T00:00:00Z',
    gender: 'Female',
    bloodGroup: 'AB+',
    contactNumber: '+880161111111',
    email: 'nadia.islam@student.edu',
    address: 'House 45, Sector 7, Rajshahi',
    emergencyContact: '+880161234567',
    medicalConditions: 'Diabetes',
    guardianId: 'g4',
    academicClassId: 'ac2',
    guardian: mockGuardians[3],
    academicClass: mockAcademicClasses[1],
    createdAt: new Date().toISOString(),
  },
  {
    id: 's5',
    firstName: 'Tariq',
    lastName: 'Rahman',
    registrationNumber: 'REG2024005',
    dateOfBirth: '2008-07-25T00:00:00Z',
    gender: 'Male',
    bloodGroup: 'A-',
    contactNumber: '+880151111111',
    email: 'tariq.rahman@student.edu',
    address: 'Apartment 2C, City Center, Dhaka',
    emergencyContact: '+880151234567',
    guardianId: 'g1',
    academicClassId: 'ac4',
    roomId: '2',
    bedId: '3',
    guardian: mockGuardians[0],
    academicClass: mockAcademicClasses[3],
    room: {
      id: '2',
      roomNumber: '102',
      floor: '1st Floor',
      building: 'Main Building',
    },
    bed: {
      id: '3',
      bedNumber: '102-A',
    },
    createdAt: new Date().toISOString(),
  },
];